[git]
conventional_commits = false
filter_unconventional = false
commit_parsers = [
  { message = "^(?i)\\[API Change\\]", group = "ğŸ’¥ API Changes" },
  { message = "^(?i)\\[Feature\\]",    group = "ğŸš€ Features"     },
  { message = "^(?i)\\[Patch\\]",      group = "ğŸ Fixes"        },
  { message = "^(?i)\\[Docs?\\]",      group = "ğŸ“š Docs"         },
  { message = "^(?i)\\[Perf\\]",       group = "âš¡ Performance"  },
  { message = "^(?i)\\[Refactor\\]",   group = "ğŸ§° Maintenance"  },
  { message = "^Merge pull request",   skip = true }
]

[changelog]
header = "# Changelog\n"
body = """
## {{ version }} - {{ timestamp | date(format="%Y-%m-%d") }}
{% for group, commits in commits | group_by(attribute="group") -%}
### {{ group }}
{% for c in commits -%}
- {{ c.message | split(pat="\\n") | first }} ({{ c.id | truncate(length=7) }})
{% endfor -%}
{% endfor -%}
"""

